# Generated by Django 4.1.5 on 2023-02-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='mountain_pass.area', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Cords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cords',
                'verbose_name_plural': 'Cords',
            },
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=100, null=True)),
                ('other_titles', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('connect', models.CharField(default='Нет информации', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'новый'), (2, 'Модератор взял в работу'), (3, 'Модерация прошла успешно'), (4, 'Модерация прошла, информация не принята')], default=1)),
                ('winter', models.CharField(blank=True, max_length=30, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=30, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=30, null=True, verbose_name='Весна')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.area')),
                ('cords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.cords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mountain Pass',
                'verbose_name_plural': 'Mountain Passes',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='media')),
                ('mountain_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.mountainpass')),
            ],
        ),
    ]
