# Generated by Django 4.1.5 on 2023-01-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerevalPhoto',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='mountainpass',
            old_name='pereval_area',
            new_name='area',
        ),
    ]
