# Generated by Django 4.1.5 on 2023-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0002_rename_perevalphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainpass',
            name='autumn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='spring',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='summer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='winter',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Зима'),
        ),
    ]
